db:
  host: netflix_postgres
#  host: localhost
  name: netflix
  port: 5432
  user: postgres
  password: qwerty

jwt:
  secret: supersecret
  accessTokenExpiryHours: 10

server:
  addr: :8000
  grpcAddr: movies-service:8085
#  grpcAddr: :8085
  grpcTimeout: 10

password:
  secret: passwordhashsecret
