version: "3.8"

services:
  proxy_server:
    container_name: proxy_server
    restart: always
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - netflix_postgres

  netflix_postgres:
    container_name: netflix_postgres
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "qwerty"
      POSTGRES_DB: netflix
    ports:
      - "5432:5432"