version: "3.8"

services:
  proxy_server:
    container_name: proxy_server
    restart: always
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - netflix_users_postgres
    networks:
      - netflix
    environment:
      DB_HOST: "netflix_users_postgres"
      DB_NAME: "netflix_users"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "qwerty"

      REDIS_ADDR: "netflix_redis:6379"
      REDIS_PASSWORD: "redisSecurePass"

      JWT_SECRET: "supersecret"
      JWT_ACCESS_TOKEN_EXPIRY_HOURS: "10"

      SERVER_ADDR: ":8000"
      GRPC_ADDR: "netflix_movies:8085"
      GRPC_TIMEOUT: "10"

      PASSWORD_SECRET: "passwordhashsecret"

      LOG_LEVEL: 6

  netflix_users_postgres:
    container_name: netflix_users_postgres
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    networks:
      - netflix
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "qwerty"
      POSTGRES_DB: "netflix_users"
    ports:
      - "5432:5432"

  netflix_redis:
    container_name: netflix_redis
    restart: always
    image: redis:latest
    command: redis-server --requirepass redisSecurePass
    volumes:
      - ./database/redis/data:/var/lib/redis/data
    networks:
      - netflix
    ports:
      - "6379:6379"


networks:
  netflix:
    external: true